---
services:
  faster-whisper:
    image: lscr.io/linuxserver/faster-whisper:latest
    container_name: faster-whisper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WHISPER_MODEL=tiny-int8
      - LOCAL_ONLY= #optional
      - WHISPER_BEAM=1 #optional
      - WHISPER_LANG=en #optional
    volumes:
      - ./whisper_data:/config
    ports:
      - 10300:10300
    restart: unless-stopped
  piper:
    #image: lscr.io/linuxserver/piper:latest
    #Per: https://github.com/linuxserver/docker-piper/issues/17#issuecomment-3263475006
    #Per: https://github.com/rhasspy/wyoming-piper/issues/20
    image: lscr.io/linuxserver/piper:1.6.3-ls75
    container_name: piper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PIPER_VOICE=en_US-lessac-medium
      - LOCAL_ONLY= #optional
      - PIPER_LENGTH=1.0 #optional
      - PIPER_NOISE=0.667 #optional
      - PIPER_NOISEW=0.333 #optional
      - PIPER_SPEAKER=0 #optional
      - PIPER_PROCS=1 #optional
      - STREAMING= #optional
    volumes:
      - ./piper_data:/config
    ports:
      - 10200:10200
    restart: unless-stopped
  openwakeword:
    image: rhasspy/wyoming-openwakeword:latest
    container_name: openwakeword
    command: ["--preload-model", "ok_nabu", "--custom-model-dir", "/custom"]
    volumes:
      - ./openwakeword_data:/custom
    ports:
      - 10400:10400
    restart: unless-stopped

